name: Package Tests

on:
  push:
  pull_request:

jobs:
  package-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: [ 'core', 'bladebones' ]
        php: [ '8.0', 8.1, 8.2 ]
        laravel: [ 9, 10 ]
        stability: [ 'prefer-lowest', 'prefer-stable' ]

    name: ${{ matrix.package }} - PHP ${{ matrix.php }} L${{ matrix.laravel }} w/ ${{ matrix.stability }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Set Minimum PHP 8.1 Versions
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require phpunit/phpunit:^9.5.8 --dev --${{ matrix.stability }} --no-update --no-interaction
            composer require vlucas/phpdotenv:^5.3.1 --${{ matrix.stability }} --no-update --no-interaction
        if: matrix.php >= 8.1 && matrix.stability == 'prefer-lowest'
        working-directory: ./packages/${{ matrix.package }}

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --no-interaction
        working-directory: ./packages/${{ matrix.package }}

      - name: Execute tests
        run: vendor/bin/phpunit
        working-directory: ./packages/${{ matrix.package }}
